[package]
name = "shark"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_16"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"